# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e91c9bb07872eda1023aa5aed4616b4e0482de985e078bbdd4373cdeabba79a3ef773bdf24ae2b1a6f7bf2c7b662136079ebd256ed2ca0af3bc2e5365eb918

test:
  secret_key_base: 1e15ebd0282b9bf6d8c1a70273575b86aba20600e146b97fe644f9229c29e7067366820aa0649def4d8870d5927a37514e25ba8966f1c49b30982b67a83e0865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
